//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "news_to_label_link")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub news_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub label_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::news::Entity",
		from = "Column::NewsId",
		to = "super::news::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	News,
	#[sea_orm(
		belongs_to = "super::news_label::Entity",
		from = "Column::LabelId",
		to = "super::news_label::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	NewsLabel,
}

impl Related<super::news::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::News.def()
	}
}

impl Related<super::news_label::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::NewsLabel.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
