//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::news::Entity as News;
pub use super::source::Entity as Source;
pub use super::source_category::Entity as SourceCategory;
pub use super::source_directory::Entity as SourceDirectory;
pub use super::source_to_category_link::Entity as SourceToCategoryLink;
