//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::news::Entity as News;
pub use super::news_apearance_signal::Entity as NewsApearanceSignal;
pub use super::news_explicit_vote_signal::Entity as NewsExplicitVoteSignal;
pub use super::news_focus_signal::Entity as NewsFocusSignal;
pub use super::news_read_signal::Entity as NewsReadSignal;
pub use super::source::Entity as Source;
pub use super::source_category::Entity as SourceCategory;
pub use super::source_directory::Entity as SourceDirectory;
pub use super::source_fetch_signal::Entity as SourceFetchSignal;
pub use super::source_to_category_link::Entity as SourceToCategoryLink;
