//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "source_to_category_link")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub source_id: Uuid,
	#[sea_orm(primary_key, auto_increment = false)]
	pub category_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::source::Entity",
		from = "Column::SourceId",
		to = "super::source::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Source,
	#[sea_orm(
		belongs_to = "super::source_category::Entity",
		from = "Column::CategoryId",
		to = "super::source_category::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	SourceCategory,
}

impl Related<super::source::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Source.def()
	}
}

impl Related<super::source_category::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::SourceCategory.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
