//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "source_fetch_signal")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub source: Uuid,
	pub done_at: TimeDateTimeWithTimeZone,
	pub duration: i32,
	pub failure_code: Option<i8>,
	pub new_items_count: i32,
	pub latest_publish_at: Option<TimeDateTimeWithTimeZone>,
	pub oldest_publish_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::source::Entity",
		from = "Column::Source",
		to = "super::source::Column::Id",
		on_update = "NoAction",
		on_delete = "Cascade"
	)]
	Source,
}

impl Related<super::source::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Source.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
