//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "source_category")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	#[sea_orm(column_type = "Text", unique)]
	pub name: String,
	#[sea_orm(column_type = "Text", nullable)]
	pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::source_to_category_link::Entity")]
	SourceToCategoryLink,
}

impl Related<super::source_to_category_link::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::SourceToCategoryLink.def()
	}
}

impl Related<super::source::Entity> for Entity {
	fn to() -> RelationDef {
		super::source_to_category_link::Relation::Source.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::source_to_category_link::Relation::SourceCategory.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
